# conf/model/denoiser_unet1d.yaml
_target_: src.models.regression_model.RegressionModel

model:
  _target_: src.models.unet_1d.UNet1D
  in_channels: 1
  out_channels: 1
  dims: [32, 64, 128, 256]
  skip_mode: on      # on | off

loss:
  _target_: torch.nn.MSELoss

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.01