# conf/model/denoiser_mlp.yaml
_target_: src.models.regression_model.RegressionModel

model:
  _target_: src.models.regressors.DenoiserOperator
  mode: baseline                 # baseline | residual | preconditioned
  preconditioner: none           # none | identity | ma | haar
  ma_kernel_size: 9
  haar_levels: 3

  net:
    _target_: src.models.regressors.MLPResNet
    input_dim: ${data.d}
    output_dim: ${data.d}
    hidden_dim: 64
    depth: 2
    dropout: 0.05
    use_layernorm: true

loss:
  _target_: torch.nn.MSELoss

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.01