_target_: models.Model

model:
  _target_: models.UNet
  in_channels: ${data.in_channels}
  out_classes: ${data.out_classes}
  dims: [8, 16, 32, 64]

scheduler:
  _target_: optim.lr_scheduler.CosineAnnealingWithWarmupLR
  warmup_epoch: 10
  decay_epoch: 300
  eta_min_ratio: 0.1

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.01
