_target_: models.Model

model:
  _target_: models.WaveletUNet
  in_channels: 1
  out_classes: 10
  stem_dim: 8
  depth: 3
  head: classification

scheduler:
  _target_: optim.lr_scheduler.CosineAnnealingWithWarmupLR
  warmup_epoch: 10
  decay_epoch: 300
  eta_min_ratio: 0.1

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.01

loss:
  _target_: torch.nn.CrossEntropyLoss

metrics:
  accuracy:
    _target_: metrics.Accuracy